# create azure pipeline to deploy bicep template

trigger: none

pool: 
  vmImage: 'ubuntu-latest'

jobs:
  - job: 'ValidateBicep'
    displayName: 'Validate Bicep'
    steps:
    - task: MicrosoftSecurityDevOps@1
      displayName: 'Microsoft Security DevOps - Validate Bicep'
      inputs:
        categories: 'IaC'
    - task: ManualValidation@0
      inputs:
        notifyUsers: 'w.viriyaampanond@outlook.com'
        instructions: 'Approve or reject Bicep deployment'
        onTimeout: reject
        timeOutInMinutes: 120
        
  - deployment: 'DeployBicepDev'
    displayName: 'Deploy Bicep Dev'
    dependsOn: 'ValidateBicep'
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AZURE_SUBSCRIPTION_NONEPROD'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create --resource-group app-$(Environment.Name)-rg --template-file ./main.bicep --parameters environmentName=$(Environment.Name) applicationName=api sku=F1

  - deployment: 'DeployBicepTest'
    displayName: 'Deploy Bicep Test'
    dependsOn: 'DeployBicepDev'
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AZURE_SUBSCRIPTION_NONEPROD'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create --resource-group app-$(Environment.Name)-rg --template-file ./main.bicep --parameters environmentName=$(Environment.Name) applicationName=api sku=F1

  - deployment: 'DeployBicepProd'
    displayName: 'Deploy Bicep Prod'
    dependsOn: 'DeployBicepTest'
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AZURE_SUBSCRIPTION_PROD'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create --resource-group app-$(Environment.Name)-rg --template-file ./main.bicep --parameters environmentName=$(Environment.Name) applicationName=api sku=F1